### ISSUE TITLE
index.ts，复习时，easy的间隔算法疑问

### ISSUE THREAD

**Issue by Ariadn4** [open-spaced-repetition/fsrs.js#10]
line 241 `let easy_interval = Math.max(
      this.next_interval(s.easy.stability * this.p.hard_factor),
      good_interval + 1
 );`
我对照fsrs4anki_scheduler.js，这里的this.p.hard_factor是不是应该更换成this.p.easy_bonus？

**Comment by oflg** [comment]
这个包是对照[py-fsrs](https://github.com/open-spaced-repetition/py-fsrs)写的。

js版的241行： https://github.com/open-spaced-repetition/fsrs.js/blob/2bbb6537808c5416d63bcc928ec4229c55c1a3d2/src/index.ts#L241

对应py版的47行：https://github.com/open-spaced-repetition/py-fsrs/blob/464543779f7e8ebaca18697cdf84fe8cd0dc766d/src/fsrs/fsrs.py#L47

state为Review时使用`hard_factor`，其他state时使用`easy_bonus`

**Comment by L-M-Sherlock** [comment]
草，我写的 bug 被发现了（
建议参考 go-fsrs

**Comment by oflg** [comment]
> 建议参考 go-fsrs

🙈

**Comment by L-M-Sherlock** [comment]
py-fsrs 没什么人用，所以 bug 没找出来。go-fsrs 目前思源笔记在用，所以帮忙看的人也比较多。
当然，bug 最少的应该是 FSRS4Anki，社区目前最活跃。

**Comment by oflg** [comment]
> 这里的this.p.hard_factor是不是应该更换成this.p.easy_bonus？

是的，已经修复https://github.com/open-spaced-repetition/fsrs.js/commit/9a937d091fac701395d20a763f69da42c4765cf5
