### ISSUE TITLE
为什么update_state时，只有new和review把lapses+=1？

### ISSUE THREAD

**Issue by Ariadn4** [open-spaced-repetition/fsrs.js#11]
`update_state(state: State) {
        if (state == State.New) {
            this.again.state = State.Learning;
            this.hard.state = State.Learning;
            this.good.state = State.Learning;
            this.easy.state = State.Review;
            this.again.lapses += 1;
        } else if (state == State.Learning || state == State.Relearning) {
            this.again.state = state;
            this.hard.state = state;
            this.good.state = State.Review;
            this.easy.state = State.Review;
        } else if (state == State.Review) {
            this.again.state = State.Relearning;
            this.hard.state = State.Review;
            this.good.state = State.Review;
            this.easy.state = State.Review;
            this.again.lapses += 1;
        }
    }`

**Comment by oflg** [comment]
参照py版的这几行写的：https://github.com/open-spaced-repetition/py-fsrs/blob/464543779f7e8ebaca18697cdf84fe8cd0dc766d/src/fsrs/models.py#L79-L96

state表示卡片的状态，有下面四种：

```
New 新的，从未学习过
Learning 学习，最近第一次学习
Review 复习，从学习状态毕业
Relearning 重新学习，在复习状态下被遗忘了
```

laspse 字段表示累计遗忘次数，卡片在学习时的遗忘不增加 lapse。

具体还是要请教算法设计者@L-M-Sherlock 叶哥，我只是改下代码语言🤣

**Comment by L-M-Sherlock** [comment]
Anki 的逻辑就是如此。FSRS 在开发之初就考虑要兼容 Anki，所以保留了这个设计。
