### ISSUE TITLE
关于算法参数w的问题

### ISSUE THREAD

**Issue by Panshaojun** [open-spaced-repetition/fsrs.js#13]
你好。请问这个w参数是固定的吗？我看这个貌似来自anki那个插件算法，w好像可以根据学习材料自动适应

**Comment by Panshaojun** [comment]
🤔，我保存有您之前的老版本，老版本的全局参数有些参数是可以自动适应的

**Comment by L-M-Sherlock** [comment]
是固定的，需要导出复习数据，才可以使用外部优化器计算参数。

**Comment by Panshaojun** [comment]
大佬你咋回复我了，我看的是这个fsrs.js。那请问这个w现在是平均的吗？也就是说是适合普通人的吧？

**Comment by Panshaojun** [comment]
我想表达的意思是，这个是默认的基础参数吧，本身就适合绝大部分人？

**Comment by L-M-Sherlock** [comment]
默认参数只是根据 SM-2 来的，并不意味着适合绝大多数人。只能说不会比 SM-2 还差。

**Comment by Panshaojun** [comment]
哈哈，好吧，我之前看到的这个老版本算法还能自适应，可现在却不能了。感觉好像是专门为anki制作的。外部优化器也找不着算法

**Comment by L-M-Sherlock** [comment]
因为之前的老版本自适应效果并不好（

另外目前已经能够给 FSRS4RemNote 优化参数了。理论上任何复习记录都可以用于优化，前提是做了复习记录持久化，并以特定格式导出。
