### ISSUE TITLE
w参数中的初始稳定度没有被使用

### ISSUE THREAD

**Issue by Newdea** [open-spaced-repetition/fsrs.js#17]
如题，与[算法描述文档](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm)不一致，是遗漏了么

![image](https://github.com/open-spaced-repetition/fsrs.js/assets/9208450/ac490f44-48e1-4618-b086-2211a31c772c)

**Comment by L-M-Sherlock** [comment]
有用到，被存入stability和difficulty了，在进入review状态时会用到。

**Comment by Newdea** [comment]
明白了，就是在新卡状态时，again/hard/good不使用w中参数，直接默认1/5/10分钟后学习
