### ISSUE TITLE
ts打包类型出错：打包后的index.d.ts文件里出现类型丢失的问题

### ISSUE THREAD

**Issue by Buzhifanji** [open-spaced-repetition/fsrs.js#18]
![image](https://github.com/open-spaced-repetition/fsrs.js/assets/28743253/ed75fa3c-769b-4ed1-8f76-4c0ec83cda5f)

打包后的index.d.ts的文件，存在三处constructor丢失类型参数的问题。

虽然可以通过下面引入

`import { Card, FSRS, Rating } from 'fsrs.js/src'`

但和Readme.md的引入示例相冲突。

使用typescript的版本号：^5.1.6

**Comment by L-M-Sherlock** [comment]
@oflg, 我对 ts 不太懂，你帮忙看看？

**Comment by oflg** [comment]
好 我瞅瞅

**Comment by asukaminato0721** [comment]
我看了下原来的 ts 文件

https://github.com/open-spaced-repetition/fsrs.js/blob/e0f4badf3a1cb28779b27beab56ae0c906ec2d9a/src/index.ts#L46

也是没有参数的。

**Comment by oflg** [comment]
我不清楚这个问题（并不太会ts），期待对ts熟悉的朋友PR，写出更好的代码🫡

**Comment by 1cedsoda** [comment]
I don't see an issue here. Looks correct, since the constructors initialize with default values, not custom ones.

**Comment by asukaminato0721** [comment]
I think this PR could be closed.
