### ISSUE TITLE
关于Card字段问题

### ISSUE THREAD

**Issue by Buzhifanji** [open-spaced-repetition/fsrs.js#19]
请教一下两个问题：

问题一： elapsed_days  和  scheduled_days  这两个字段是什么意思？

问题二：从 ReviewLog 里提取复习数据算法逻辑是咋样的？

**Comment by L-M-Sherlock** [comment]
scheduled_days 是算法安排的间隔，elapsed_days 是举例上次复习真正过去的间隔

**Comment by L-M-Sherlock** [comment]
将用于训练的复习数据格式请见：https://github.com/open-spaced-repetition/fsrs-optimizer#review-logs-schema

**Comment by Buzhifanji** [comment]
ok，明白了，非常感谢的解答
