### ISSUE TITLE
Optimizer for other apps

### ISSUE THREAD

**Issue by filipenanclarez** [open-spaced-repetition/fsrs.js#20]
Hi,

I’m a dev. And your research is amazing.

I want make a flashcard app. Anki is also amazing but have their limitations.

If i make this, I want to know…

can I use your optimizer ML model in my app?

I know you have a site to run this. But regular users avoid this advanced method. They only want use the best algo without worries about how and when optimize their decks.

Most of them choose memrise or Duolingo because this apps is easy to use.

So, is you ML model open? Can I use your model like .tflite format? 

The idea is make a cross platform flashcard app, like Anki, but with automated optimize process, so users can have the benefits of fully potential of you research.

**Comment by L-M-Sherlock** [comment]
You can consider to use these lib:
- https://github.com/open-spaced-repetition/fsrs-optimizer
- https://github.com/open-spaced-repetition/fsrs-optimizer-burn

I haven't used tensorflow, so you can implement one for your project.

**Comment by L-M-Sherlock** [comment]
By the way, we are integrating FSRS Optimizer into Anki:
- https://github.com/ankitects/anki/pull/2633

**Comment by filipenanclarez** [comment]
> By the way, we are integrating FSRS Optimizer into Anki:
> 
> * [Integrate the FSRS optimizer ankitects/anki#2633](https://github.com/ankitects/anki/pull/2633)

This will works on mobile too? (ie.: AnkiDroid and AnkiMobile)

**Comment by L-M-Sherlock** [comment]
> This will works on mobile too? (ie.: AnkiDroid and AnkiMobile)

Yeah. It's implemented in Rust, which will be used for cross-platform.

**Comment by filipenanclarez** [comment]
Thank you for feedback, i'll look your links.

**Comment by filipenanclarez** [comment]
> By the way, we are integrating FSRS Optimizer into Anki:
> 
> * [Integrate the FSRS optimizer ankitects/anki#2633](https://github.com/ankitects/anki/pull/2633)

Can i help with tests ?

**Comment by L-M-Sherlock** [comment]
Of course, test is welcomed.

**Comment by filipenanclarez** [comment]
> 

How can i have access to this beta commit?

**Comment by L-M-Sherlock** [comment]
You can use git to clone the repo and checkout the fsrs branch.
