### ISSUE TITLE
Use FSRS for a word learning app.

### ISSUE THREAD

**Issue by Sumis34** [open-spaced-repetition/fsrs.js#26]
Hey, 

I would love to use this algorithem for my App. I have been looking at alot of documentation but I cant put the pieces together.

What I want to achive:

1. Have a list of Words with anser and question
2. Verify the correctnes of the answer and reate the review accordingly
3. Get the next Card one after the other. (Not just the ones due today. If they run out just get the next best card)

Can you help me get a basic setup done with fsrs.js (List of cards, getNextCard....). Is it even a good fit for this usecase?

**Comment by L-M-Sherlock** [comment]
FSRS is only responsible for long-term schedule. For your case, you need to design the short-term scheduler in your app. Here is a repo which uses FSRS: https://github.com/siyuan-note/riff

**Comment by Sumis34** [comment]
Thanks for your reply. Do you know of any good solution for a short-term scheduler? Leinter System?

**Comment by L-M-Sherlock** [comment]
I don't know. Anki has a complex short-term scheduler. You can read the introduction here: https://www.juliensobczak.com/inspect/2022/05/30/anki-srs.html
