### ISSUE TITLE
从1.1.0更新到1.2.0后，无法引用 ReviewLog 类

### ISSUE THREAD

**Issue by Newdea** [open-spaced-repetition/fsrs.js#29]
在1.1.0版时，可正常引用类 ReviewLog
但更新后，无法引用，类 ReviewLog 没有导出

**Comment by oflg** [comment]
是的。

因为之前我觉得可以用下面代码获取review log，这样导出ReviewLog类就多余了，于是在更新的时候把它去掉。

```
//Get the review log after rating `Good`:
review_log = scheduling_cards[rating.Good].review_log
```

现在不能导出，产生了什么问题吗？如果有，我就再加上。

**Comment by Newdea** [comment]
想用来声明变量类型，但没有这个导出类就报错了。 或有没其他方法

https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/blob/eb9dcd7f585150f7f002fe32a1adeef295351d0a/src/algorithms/fsrs.ts#L23

**Comment by oflg** [comment]
我再改回去吧，一会发一版。

**Comment by oflg** [comment]
已发布v1.2.1：https://github.com/open-spaced-repetition/fsrs.js/commit/b7c278f87ab5e9a96e8c91a27caa7cf21bbf111b

**Comment by Newdea** [comment]
多谢，现在可以正常引用了
