### ISSUE TITLE
docs: Add information about implemented version of FSRS

### ISSUE THREAD

**Issue by jkazimierczak** [open-spaced-repetition/fsrs.js#30]
Current README lacks description of which version of FSRS is implemented. As described in [the algorithm wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm), FSRS has multiple versions:
- FSRS-4.5,
- FSRS v4,
- FSRS v3.

It would be good if this was specified in README.

**Comment by oflg** [comment]
@L-M-Sherlock I just realized that FSRS was updated to v4.5, so the version implemented in fsrs.js is now FSRSv4?

**Comment by L-M-Sherlock** [comment]
Yeah. It's FSRSv4.

**Comment by oflg** [comment]
Done. 😎

![image](https://github.com/open-spaced-repetition/fsrs.js/assets/42492105/b484891d-8b45-44c9-8943-ac2224bd550b)
