### ISSUE TITLE
Feature request: port this algorithm to work with anki custom scheduling

### ISSUE THREAD

**Issue by Vilhelm-Ian** [open-spaced-repetition/fsrs.js#5]
Recently anki added the option to add custom scheduling algorithms using javascript per deck. It would be nice if this algorithm could just be pasted into anki

**Comment by oflg** [comment]
I'm mostly focused on TiddlyWiki, @L-M-Sherlock  might be working on anki custom scheduling.

**Comment by L-M-Sherlock** [comment]
The new scheduler of Anki changes a lot. I'm still working on a new adaptive algorithm for individuals. Maybe I will find it out how to migrate the FSRS to Anki.

https://faqs.ankiweb.net/the-2021-scheduler.html

**Comment by L-M-Sherlock** [comment]
I have asked about some problems in porting this algorithm to work with Anki's custom scheduling

https://forums.ankiweb.net/t/some-problems-in-implementing-a-state-of-the-art-srs-scheduler-on-anki/22705

**Comment by Vilhelm-Ian** [comment]
THANK YOU VERY MUCH 🥰

**Comment by L-M-Sherlock** [comment]
I implement a simplified version of fsrs for Anki. Maybe it is useful to you.

https://github.com/open-spaced-repetition/fsrs4anki
