### ISSUE TITLE
Question about grades

### ISSUE THREAD

**Issue by marklundin** [open-spaced-repetition/fsrs.js#6]
Apologies for my lack of understanding, but are the grades designed to be user selected in response to a given card? I'm trying to understand what the inputs and ouputs of this are. Is it correct to assume that for any given card graded between 0 - 2 fsrs will compute the next suggested interval? I'm hoping to use this in a scenario where a user simply answers correct or not, and this is used as a grade

**Comment by L-M-Sherlock** [comment]
`Grade == 0` means an incorrect answer. In your case, you can map the correct answer to `Grade == 2`.
