### ISSUE TITLE
More information about the algorithm

### ISSUE THREAD

**Issue by blasco** [open-spaced-repetition/fsrs.js#9]
First of all, thank you for such a great work! I think it would be useful to add more details regarding the implemented algorithm.

For example, what is the intended ussage of globalData? Is this something that should be store per study session or how does it work?

What do the different parameters in global data affect and control?
`
                difficultyDecay: -0.7,
                stabilityDecay: -0.2,
                increaseFactor: 60,
                requestRetention: 0.9,
                totalCase: 0,
                totalDiff: 0,
                totalReview: 0,
                defaultDifficulty: 5,
                defaultStability: 2,
                stabilityDataArry: []
`

I'm specially confused about the intention of the cumulative parameters: 
`
                totalCase: 0,
                totalDiff: 0,
                totalReview: 0,
`

These change after each card reviewed, are they supposed to be stored? What do they model and how do they affect? 

I think we need more open learning algorithm like this one, once again thank you for your great work!

**Comment by oflg** [comment]
Thank you for exploring the algorithm. 

globalData stores the default initial parameters of the algorithm. These parameters are from the earlier FSRS algorithm (https://github.com/open-spaced-repetition/free-spaced-repetition-scheduler/tree/0f9995853b6b826120ec79da093dbb7a275d8d0c), the link has the detailed algorithm code and readme. 

View https://github.com/open-spaced-repetition/free-spaced-repetition-scheduler/blob/0f9995853b6b826120ec79da093dbb7a275d8d0c/simulator.py#L11 and https://github.com/open-spaced-repetition/free-spaced-repetition-scheduler/blob/0f9995853b6b826120ec79da093dbb7a275d8d0c/simulator.py#L126 to find these parameters.
